name: SonarCloud
on:
  pull_request:
    branches: [develop, staging, release]
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build --if-present

      - name: Run Tests
	run: yarn jest --clearCache
        run: yarn test:ci
        env:
          REACT_APP_API_URL: https://devapi.mozork.com

      - name: Fix code coverage paths for Sonar
        working-directory: ./coverage
        run: |
          sed -i 's/\/home\/runner\/work\/IXWebApp\/IXWebApp\//\/github\/workspace\//g' lcov.info
          sed -i 's/\/home\/runner\/work\/IXWebApp\/IXWebApp\//\/github\/workspace\//g' test-report.xml

      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
